import { useState, useEffect, useRef, useCallback } from 'react';
import * as tf from '@tensorflow/tfjs';
import { CLASS_LABELS } from '../data/labels';

const MODEL_URL = '/model/model.json';
const LABELS_URL = '/model/labels.json';

/**
 * useInference — loads the TFJS model at startup and exposes a `predict` function.
 *
 * Design notes:
 * - Model is loaded once and kept in memory; subsequent calls are fast (~100-200ms).
 * - A warmup pass (zeros tensor) is run after load so the first real prediction
 *   doesn't pay the JIT compilation cost.
 * - We use tf.tidy() to automatically dispose intermediate tensors and avoid
 *   WebGL memory leaks.
 * - If labels.json is present in /model/, it overrides the hardcoded CLASS_LABELS
 *   fallback. This ensures the app stays correct even if you retrain the model.
 * - MobileNetV2 expects inputs in the range [-1, 1] (not [0, 1]).
 *   Preprocessing: pixel / 127.5 - 1.0.
 */
export function useInference() {
  const [status, setStatus] = useState('idle'); // 'idle' | 'loading' | 'ready' | 'error'
  const [loadError, setLoadError] = useState(null);
  const modelRef = useRef(null);
  const labelsRef = useRef(CLASS_LABELS); // fallback to hardcoded labels

  // Load model + labels on mount
  useEffect(() => {
    let cancelled = false;

    async function load() {
      setStatus('loading');
      try {
        // 1. Attempt to load dynamic labels.json (generated by Colab notebook)
        try {
          const res = await fetch(LABELS_URL);
          if (res.ok) {
            const dynamicLabels = await res.json();
            // dynamicLabels is expected to be an array: ["class_key", ...]
            if (Array.isArray(dynamicLabels) && dynamicLabels.length > 0) {
              labelsRef.current = dynamicLabels;
            }
          }
        } catch {
          // labels.json missing → use hardcoded CLASS_LABELS fallback (fine for demo)
          console.info('labels.json not found, using hardcoded fallback.');
        }

        // 2. Load TFJS model
        const model = await tf.loadLayersModel(MODEL_URL);

        // 3. Warmup pass — avoids slow first prediction from WebGL JIT
        const dummy = tf.zeros([1, 224, 224, 3]);
        const warmupOut = model.predict(dummy);
        await warmupOut.data();
        dummy.dispose();
        warmupOut.dispose();

        if (!cancelled) {
          modelRef.current = model;
          setStatus('ready');
        }
      } catch (err) {
        if (!cancelled) {
          console.error('Model load failed:', err);
          setLoadError(err.message);
          setStatus('error');
        }
      }
    }

    load();
    return () => { cancelled = true; };
  }, []);

  /**
   * predict(imageElement) → { classKey, displayIndex, confidence, allProbs, labels }
   *
   * @param {HTMLImageElement|HTMLCanvasElement|ImageData} imageElement
   *   Any image source that tf.browser.fromPixels accepts.
   */
  const predict = useCallback(async (imageElement) => {
    if (!modelRef.current) {
      throw new Error('Model is not loaded yet. Please wait.');
    }

    // Run in tf.tidy to auto-dispose all intermediate tensors
    const result = tf.tidy(() => {
      // fromPixels → [H, W, 3] uint8
      const img = tf.browser.fromPixels(imageElement);

      // Resize to 224×224 (MobileNetV2 input size)
      const resized = tf.image.resizeBilinear(img, [224, 224]);

      // Normalize to [-1, 1] — MobileNetV2 preprocessing
      const normalized = resized.toFloat().div(tf.scalar(127.5)).sub(tf.scalar(1.0));

      // Add batch dimension: [1, 224, 224, 3]
      const batched = normalized.expandDims(0);

      // Inference
      const predictions = modelRef.current.predict(batched);
      const probs = Array.from(predictions.dataSync());

      // Find top prediction
      const maxIdx = probs.indexOf(Math.max(...probs));
      const confidence = probs[maxIdx];
      const classKey = labelsRef.current[maxIdx] ?? `unknown_${maxIdx}`;

      return {
        classKey,
        displayIndex: maxIdx,
        confidence,          // 0.0 → 1.0
        allProbs: probs,
        labels: labelsRef.current,
      };
    });

    return result;
  }, []);

  return {
    status,      // 'idle' | 'loading' | 'ready' | 'error'
    loadError,
    predict,
    isReady: status === 'ready',
    isLoading: status === 'loading',
  };
}
